services:
  litorganizer:
    image: bcankara/litorganizer:v2
    container_name: litorganizer
    ports:
      - "5000:5000"
    volumes:
      - ./pdfs:/app/pdf
      - ./processed:/app/processed
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
